#!/usr/bin/env bash

set -e
shopt -s extglob

info() { echo "[info] $1"; }

ROOT="${PWD}"
STAGING="${ROOT}/staging"
PACKAGES="${ROOT}/packages"
export INSTALLPREFIX="${STAGING}/prefix/linux/iphone"
if [[ -x $(command -v nproc) ]]; then
	export JOBS=$(nproc --all)
elif [[ -x $(command -v sysctl) ]]; then
	export JOBS=$(sysctl -n hw.ncpu)
else
	export JOBS=1
fi

info "Creating prefix dir"
rm -rf "${STAGING}"
mkdir -pv "${INSTALLPREFIX}"

info "Building LLVM tools"
cd "${ROOT}/apple-libtapi/"
cmake -B build -S src/llvm \
	-DLLVM_ENABLE_PROJECTS="tapi;clang" \
	-DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_ENABLE_WARNINGS=OFF \
	-DTAPI_FULL_VERSION="$(cat $PWD/VERSION.txt | grep "tapi" | grep -o '[[:digit:]].*')" \
	-DCMAKE_CXX_FLAGS="-I${PWD}/src/llvm/projects/clang/include/ -I${PWD}/build/projects/clang/include/" \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-DCMAKE_INSTALL_PREFIX="${INSTALLPREFIX}"
cmake --build build --target install-libtapi install-tapi-headers install-tapi install-dsymutil -- -j "${JOBS}"

info "Building libdispatch"
cd "${ROOT}/apple-libdispatch"
cmake -B build \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="$INSTALLPREFIX" \
	.
make -j "${JOBS}" install

info "Building cctools"
cd "${ROOT}/cctools-port/cctools"
./configure \
	--prefix="${INSTALLPREFIX}" \
	--with-libtapi="${INSTALLPREFIX}" \
	--with-libdispatch="${INSTALLPREFIX}" \
	--with-libblocksruntime="${INSTALLPREFIX}" \
	--target="aarch64-apple-darwin14" \
	--program-prefix="" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-rpath,'\$\$ORIGIN/../lib64' -Wl,-z,origin"
make -j "${JOBS}" \
	PROGRAM_PREFIX="" \
	CXXABI_LIB="-l:libc++abi.a" \
	install

info "Building libplist"
cd "${ROOT}/libplist"
PLIST_PREFIX="${STAGING}/libplist-install"
mkdir -p "${PLIST_PREFIX}"
LC_ALL=C ./autogen.sh --prefix="${PLIST_PREFIX}" --without-cython --enable-static --disable-shared PACKAGE_VERSION=latest
make -j "${JOBS}" install
cp -av "${PLIST_PREFIX}/bin/plistutil" "${INSTALLPREFIX}/bin"

info "Installing ldid"
cd "${ROOT}/ldid"
make -j "${JOBS}" \
	DESTDIR="${INSTALLPREFIX}" PREFIX="" \
	LIBCRYPTO_LIBS="-l:libcrypto.a -lpthread -ldl" \
	LIBPLIST_LIBS="${PLIST_PREFIX}/lib/libplist-2.0.a" LIBPLIST_INCLUDES="-I${PLIST_PREFIX}/include" \
	install

info "Packaging toolchain"
mkdir -p "${PACKAGES}"
tar -czf "${PACKAGES}/darwin-tools.tar.gz" -C "${STAGING}/prefix" linux
info "Done!"
