name: Create Release

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Create Release
      run: |
        set -x
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"

  build:
    needs: create_release
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true

    - name: Build Release
      id: build_release
      run: |
        curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash -s -- 14
        sudo apt install -y --no-install-recommends clang-14 libc++-14-dev libc++abi-14-dev
        CC=clang-14 CXX=clang++-14 ./prepare-toolchain && mv packages/darwin-tools.tar.gz packages/darwin-tools-${{ matrix.os }}.tar.gz

    - name: Attach Build To Release
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release upload "$TAG" packages/darwin-tools-${{ matrix.os }}.tar.gz
