name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    # https://github.com/actions/create-release/issues/14#issuecomment-555379810
    runs-on: ubuntu-20.04
    steps:
    - name: Setup
      id: setup
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.setup.outputs.tag }}
        body: ''
        draft: true
    - name: Save Upload URL to File
      run: printf "%s" "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
    - name: Save Upload URL as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: upload_url
        path: upload_url.txt

  build:
    needs: create_release
    strategy:
      matrix:
        os:
          - runner: ubuntu-20.04
            name: ubuntu20.04
          - runner: ubuntu-18.04
            name: ubuntu18.04
    runs-on: ${{ matrix.os.runner }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Fetch Upload URL
      uses: actions/download-artifact@v2
      with:
        name: upload_url
    - name: Build Release
      id: build_release
      run: |
        echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        echo "::set-output name=upload_url::$(cat upload_url.txt)"
        rm upload_url.txt
        ./prepare-toolchain
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.build_release.outputs.upload_url }}
        asset_path: packages/darwin-tools.tar.gz
        asset_name: darwin-tools-${{ matrix.os.name }}.tar.gz
        asset_content_type: application/gzip
